# Generated by Django 3.1.7 on 2021-03-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=75, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss')], max_length=5, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=150, null=True)),
                ('address1', models.CharField(max_length=150, null=True)),
                ('address2', models.CharField(max_length=150, null=True)),
                ('city', models.CharField(max_length=75, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zip_code', models.CharField(max_length=30, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
