# Generated by Django 3.1.7 on 2021-03-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0002_auto_20210330_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
