# Generated by Django 3.1.7 on 2021-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelope', '0004_auto_20210330_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss.', 'Miss'), ('', '')], default='', max_length=6, null=True),
        ),
    ]
